apiVersion: v1
kind: Service
metadata:
  name: sample-docs
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app: sample-docs
spec:
  selector:
    app: sample-docs
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
