apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app: sample-docs
spec:
  selector:
    matchLabels:
      app: sample-docs
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sample-docs
    spec:
      restartPolicy: Always
      containers:
      - name: sample-docs
        image: {{ .Values.image }}
        imagePullPolicy: IfNotPresent
        resources:
            limits:
              memory: 256Mi
            requests:
              memory: 256Mi
              cpu: "0.2"
        ports:
          - containerPort: 8000
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        securityContext:
          readOnlyRootFilesystem: true
          runAsGroup: 1001
          runAsUser: 1001
        volumeMounts:
          - name: config-vol
            mountPath: /docs
          - name: content-vol
            mountPath: /docs/docs
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: content-vol
          configMap:
            name: sample-docs-configmap-content
        - name: config-vol
          configMap:
            name: sample-docs-configmap
        - name: tmp
          emptyDir: {}
